version: '3.8'

services:
  web:
    build: .
    ports:
      - "80:80"
    volumes:
      -  ${VOLUME_PATH}:/code
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "80", "--reload"]